### ISSUE TITLE
UNKNOWN_APP issue

### ISSUE THREAD

**Issue by pierrea** [aligorithm/logdna_flutter#4]
Hi,
First off, thank you for being so responsive with my PR contributions!
Version 1.1.1 works well, except that we're seeing `UNKNOWN_APP` in our logs. Example below:

<img width="899" alt="UNKNOWN_APP" src="https://user-images.githubusercontent.com/1298460/147753629-4ba69d70-9d68-4698-af1e-2f9d6a3bb14b.png">

Do you know what would be missing? 
We're passing the app name in the `app` parameter of the `DnaLine`.
Thanks in advance for your help.

**Comment by aligorithm** [comment]
Hello, I appreciate your contributions! I'll check this out and hopefully we can solve this soon

**Comment by aligorithm** [comment]
I have found the problem. The appName that was removed from the `LogDna` object is still being used. We have 2 options:

1. Add the appName object back as an optional parameter and use it universally (unless specified by the `DnaLine`
2. Use the app provided in the `DnaLine` always.

I prefer option 1 because it means developers can choose to have a universal app name specified in `LogDna`, or specify it in every `DnaLine`. What do you think?

**Comment by pierrea** [comment]
What's strange is that I tested adding back `appName` as a LogDNA object parameter and the problem remains. The problem also exists even when providing `app` in `DnaLine`.

**Comment by aligorithm** [comment]
This is very strange. It works using `app` in the lines when testing with Postman, but it doesn't work from Flutter. Both log level and app name aren't showing.
<img width="849" alt="image" src="https://user-images.githubusercontent.com/23584562/147775948-c7c5085c-cf64-40ef-9340-c73f8175bbc8.png">

Still investigating...

**Comment by aligorithm** [comment]
We aren't setting headers currently. Setting the json headers solves it!
<img width="403" alt="image" src="https://user-images.githubusercontent.com/23584562/147777924-4f9e061a-6875-46ae-a007-289e414fd72f.png">
I'll push an update soon

**Comment by aligorithm** [comment]
Version 1.1.2 solves this issue! Thanks for raising this @pierrea

**Comment by aligorithm** [comment]
Though not urgent, I think the app name should be in the `LogDNA` object but configurable in `DnaLine` so you wouldn't have to set it every single time for the same app.

**Comment by pierrea** [comment]
Thank you!
And you're absolutely right about the app name in the `LogDNA` object as opposed to every time in `DnaLine`, I was thinking about proposing this improvement. Will do!
