### ISSUE TITLE
Printing true on each log sent

### ISSUE THREAD

**Issue by ArchOrn** [aligorithm/logdna_flutter#5]
Hello,

First of all, thank you for this good plugin, it is very useful :)
It is not really a big issue, but the `LogDNA.log()` function is printing `true` every time it is executed properly. It is flooding my logs while debugging and I do not really see why it is there :/

Have a nice day :)

**Comment by aligorithm** [comment]
Hello,

Thanks for your kind words. It indeed prints true, which was probably done while debugging or something. It's an easy fix that I can implement soon. Thanks for raising this.

**Comment by Rohithgilla12** [comment]
@ArchOrn 
Created a PR, if someone stumbles upon this issue, can use this branch until the PR is merged!
```
  logdna:
    git:
      url: https://github.com/Rohithgilla12/logdna_flutter
```

**Comment by aligorithm** [comment]
Thank you @Rohithgilla12 I have merged. Will create a new release soon
